# Jekyll
theme: jekyll-theme-minimal

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Site data
title: Alvin Kerber
description: math and computers and stuff
